name: Deploy React App with SonarQube Analysis

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PRs to main branch

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./  # Ensure commands run in the repo directory
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the latest stable Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Verify Installed Packages
        run: npm list react-scripts

      - name: Build React App
        run: npm run build
        env:
          CI: false  # Prevents build failures due to warnings

  sonar_scan:
    needs: build
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./  # Ensure correct directory context
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Analysis
        env:
          SONAR_HOST_URL: "http://localhost:9000"  # Update if different
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-react-app \
            -Dsonar.sources=src \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_LOGIN

  deploy:
    needs: sonar_scan
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./  # Ensure correct working directory
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Install Dependencies
        run: npm install

      - name: Verify Installed Packages
        run: npm list react-scripts

      - name: Build React App
        run: npm run build
        env:
          CI: false  # Prevents build failures due to warnings

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=build --prod
